/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student_management_system;
import java.awt.event.*;
import java.awt.*;
import javax.swing.*;
import java.sql.*;
/**
 *
 * @author Hanseeka Dhingana
 */
public class Add_student extends javax.swing.JFrame {

    /**
     * Creates new form Add_student
     */
    public Add_student() {
        setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        exit_btn1 = new javax.swing.JButton();
        home_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        dept_lbl = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        roll_lbl = new javax.swing.JLabel();
        roll_txt = new javax.swing.JTextField();
        dept_txt = new javax.swing.JTextField();
        name_txt = new javax.swing.JTextField();
        grade_txt = new javax.swing.JTextField();
        add_btn = new javax.swing.JButton();
        grade_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student_management_system/add_new-removebg-preview.png"))); // NOI18N
        jLabel5.setText(" ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(220, 33, 154, 154);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Add Student");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(352, 66, 528, 110);

        exit_btn1.setBackground(new java.awt.Color(0, 0, 0));
        exit_btn1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        exit_btn1.setForeground(new java.awt.Color(255, 255, 255));
        exit_btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student_management_system/cross-removebg-preview.png"))); // NOI18N
        exit_btn1.setContentAreaFilled(false);
        exit_btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(exit_btn1);
        exit_btn1.setBounds(1122, 11, 66, 66);

        home_btn.setBackground(new java.awt.Color(0, 0, 0));
        home_btn.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        home_btn.setForeground(new java.awt.Color(255, 255, 255));
        home_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student_management_system/home-removebg-preview.png"))); // NOI18N
        home_btn.setContentAreaFilled(false);
        home_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_btnActionPerformed(evt);
            }
        });
        jPanel1.add(home_btn);
        home_btn.setBounds(11, 11, 99, 77);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        dept_lbl.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        dept_lbl.setText("Department:");
        jPanel2.add(dept_lbl);
        dept_lbl.setBounds(275, 198, 198, 33);

        lbl_name.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lbl_name.setText("Student Name:");
        jPanel2.add(lbl_name);
        lbl_name.setBounds(275, 66, 198, 33);

        roll_lbl.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        roll_lbl.setText("Roll Number:");
        jPanel2.add(roll_lbl);
        roll_lbl.setBounds(275, 132, 198, 33);

        roll_txt.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        roll_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roll_txtActionPerformed(evt);
            }
        });
        jPanel2.add(roll_txt);
        roll_txt.setBounds(495, 132, 308, 44);

        dept_txt.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jPanel2.add(dept_txt);
        dept_txt.setBounds(495, 198, 308, 44);

        name_txt.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jPanel2.add(name_txt);
        name_txt.setBounds(495, 66, 308, 44);

        grade_txt.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        grade_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grade_txtActionPerformed(evt);
            }
        });
        jPanel2.add(grade_txt);
        grade_txt.setBounds(495, 275, 308, 44);

        add_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student_management_system/add-removebg-preview.png"))); // NOI18N
        add_btn.setContentAreaFilled(false);
        add_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });
        jPanel2.add(add_btn);
        add_btn.setBounds(660, 341, 143, 44);

        grade_lbl.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        grade_lbl.setText("Grade:");
        jPanel2.add(grade_lbl);
        grade_lbl.setBounds(275, 275, 198, 33);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1220, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void roll_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roll_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roll_txtActionPerformed

    private void grade_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grade_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grade_txtActionPerformed

    private void exit_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btn1ActionPerformed
        String message = "Do you want to exit";
        JLabel messageLabel = new JLabel(message);
        messageLabel.setFont(new Font("Trebuchet MS", Font.PLAIN, 24)); 
        int check =JOptionPane.showConfirmDialog(null,messageLabel,"Confirmation", JOptionPane.YES_NO_OPTION);
        
        if(check==JOptionPane.YES_OPTION)
        {
            
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
         Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
        }
    }//GEN-LAST:event_exit_btn1ActionPerformed

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
       if(enterData())
       {
               String name = name_txt.getText();
               int roll_Num = Integer.valueOf(roll_txt.getText());
               String dept = dept_txt.getText();
               String grade = grade_txt.getText();
       
        
       try{
               Connection connection = ConnectionProvider.getCon();
               Statement statement = connection.createStatement();
           
               statement.executeUpdate("insert into student_registor(Student_name,Roll_number,Student_depart,Student_grade) Values('"+name+"','"+roll_Num+"','"+dept+"','"+grade+"')");
               String message = "Data Successfully Entered";
               JLabel messageLabel = new JLabel(message);
               messageLabel.setFont(new Font("Trebuchet MS", Font.PLAIN, 24)); 
               JOptionPane.showMessageDialog(null, messageLabel);       
             
       }
       catch(Exception e)
       {
               JOptionPane.showMessageDialog(null, e);
       }
        
          clearData();
       }
        
    }//GEN-LAST:event_add_btnActionPerformed

    private void home_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_btnActionPerformed
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);

        Student_management_system open = new Student_management_system();
        open.setVisible(true);
    }//GEN-LAST:event_home_btnActionPerformed

    private boolean enterData(){
       if(name_txt.getText().trim().isEmpty()){
               String message = "Please Enter Student Name";
               JLabel messageLabel = new JLabel(message);
               messageLabel.setFont(new Font("Trebuchet MS", Font.PLAIN, 24)); 
               JOptionPane.showMessageDialog(null, messageLabel);       
               name_txt.grabFocus();
               return false;
        }
       if(roll_txt.getText().trim().isEmpty())
        {
               String message = "Please Enter Student Roll Number";
               JLabel messageLabel = new JLabel(message);
               messageLabel.setFont(new Font("Trebuchet MS", Font.PLAIN, 24)); 
               JOptionPane.showMessageDialog(null, messageLabel);       
               roll_txt.grabFocus();
               return false;
        }
       if(dept_txt.getText().trim().isEmpty())
        {       
               String message = "Please Enter Student Department";
               JLabel messageLabel = new JLabel(message);
               messageLabel.setFont(new Font("Trebuchet MS", Font.PLAIN, 24)); 
               JOptionPane.showMessageDialog(null, messageLabel);       
               dept_txt.grabFocus();
               return false;
        }
       if(grade_txt.getText().trim().isEmpty())
        {
               String message = "Please Enter Student Grade";
               JLabel messageLabel = new JLabel(message);
               messageLabel.setFont(new Font("Trebuchet MS", Font.PLAIN, 24)); 
               JOptionPane.showMessageDialog(null, messageLabel);       
               grade_txt.grabFocus();
               return false;
        }
        return true;
    }
            
    private void clearData()
    {
        name_txt.setText("");          roll_txt.setText("");
        dept_txt.setText("");          grade_txt.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    private javax.swing.JLabel dept_lbl;
    private javax.swing.JTextField dept_txt;
    private javax.swing.JButton exit_btn1;
    private javax.swing.JLabel grade_lbl;
    private javax.swing.JTextField grade_txt;
    private javax.swing.JButton home_btn;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JTextField name_txt;
    private javax.swing.JLabel roll_lbl;
    private javax.swing.JTextField roll_txt;
    // End of variables declaration//GEN-END:variables
}
