/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student_management_system;

import java.awt.event.*;
import java.awt.*;
import javax.swing.*;
import java.sql.*;
/**
 *
 * @author Hanseeka Dhingana
 */
public class Delete_student extends javax.swing.JFrame {

    /**
     * Creates new form Delete_student
     */
    public Delete_student() {
        setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        home_btn = new javax.swing.JButton();
        exit_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        dept_lbl = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        roll_lbl = new javax.swing.JLabel();
        roll_txt = new javax.swing.JTextField();
        dept_txt = new javax.swing.JTextField();
        name_txt = new javax.swing.JTextField();
        dlt_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student_management_system/dlt-removebg-preview.png"))); // NOI18N
        jLabel5.setText(" ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(110, 44, 396, 143);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Delete Student");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(374, 77, 528, 110);

        home_btn.setBackground(new java.awt.Color(0, 0, 0));
        home_btn.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        home_btn.setForeground(new java.awt.Color(255, 255, 255));
        home_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student_management_system/home-removebg-preview.png"))); // NOI18N
        home_btn.setContentAreaFilled(false);
        home_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_btnActionPerformed(evt);
            }
        });
        jPanel1.add(home_btn);
        home_btn.setBounds(11, 11, 99, 77);

        exit_btn.setBackground(new java.awt.Color(0, 0, 0));
        exit_btn.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        exit_btn.setForeground(new java.awt.Color(255, 255, 255));
        exit_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student_management_system/cross-removebg-preview.png"))); // NOI18N
        exit_btn.setContentAreaFilled(false);
        exit_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });
        jPanel1.add(exit_btn);
        exit_btn.setBounds(1133, 11, 66, 66);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        dept_lbl.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        dept_lbl.setText("Department:");
        jPanel2.add(dept_lbl);
        dept_lbl.setBounds(286, 209, 198, 33);

        lbl_name.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lbl_name.setText("Student Name:");
        jPanel2.add(lbl_name);
        lbl_name.setBounds(286, 77, 198, 33);

        roll_lbl.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        roll_lbl.setText("Roll Number:");
        jPanel2.add(roll_lbl);
        roll_lbl.setBounds(286, 143, 198, 33);

        roll_txt.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        roll_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roll_txtActionPerformed(evt);
            }
        });
        jPanel2.add(roll_txt);
        roll_txt.setBounds(506, 143, 308, 44);

        dept_txt.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jPanel2.add(dept_txt);
        dept_txt.setBounds(506, 209, 308, 44);

        name_txt.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jPanel2.add(name_txt);
        name_txt.setBounds(506, 77, 308, 44);

        dlt_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student_management_system/delete.jpg"))); // NOI18N
        dlt_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dlt_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlt_btnActionPerformed(evt);
            }
        });
        jPanel2.add(dlt_btn);
        dlt_btn.setBounds(660, 286, 165, 44);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1220, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void roll_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roll_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roll_txtActionPerformed

    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
      String message = "Do you want to exit";
        JLabel messageLabel = new JLabel(message);
        messageLabel.setFont(new Font("Trebuchet MS", Font.PLAIN, 24)); 
        int check =JOptionPane.showConfirmDialog(null,messageLabel,"Confirmation", JOptionPane.YES_NO_OPTION);
        
        if(check==JOptionPane.YES_OPTION)
        {
            
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
         Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
        }
    }//GEN-LAST:event_exit_btnActionPerformed

    private void home_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_btnActionPerformed
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
        
        Student_management_system open = new Student_management_system();
        open.setVisible(true);
    }//GEN-LAST:event_home_btnActionPerformed

    private void dlt_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlt_btnActionPerformed
         if(enterData())
       {
               String name = name_txt.getText();
               int roll_Num = Integer.valueOf(roll_txt.getText());
               String dept = dept_txt.getText();
               
        try{
               Connection connection = ConnectionProvider.getCon();
               Statement statement = connection.createStatement();
           
               String query = "DELETE FROM student_registor WHERE Student_name = '" + name + "' AND Roll_number = '" + roll_Num + "' AND Student_depart = '" + dept + "'";
               statement.executeUpdate(query);
           
               String message = "Data Succesfully Deleted";
               JLabel messageLabel = new JLabel(message);
               messageLabel.setFont(new Font("Trebuchet MS", Font.PLAIN, 24)); 
               JOptionPane.showMessageDialog(null, messageLabel);       
       }
        catch(Exception e)
        {
               JOptionPane.showMessageDialog(null, e);       
        }
          clearData();
       }
    }//GEN-LAST:event_dlt_btnActionPerformed
  
    
    private boolean enterData(){
       if(name_txt.getText().trim().isEmpty()){
               String message = "Please Enter Student Name";
               JLabel messageLabel = new JLabel(message);
               messageLabel.setFont(new Font("Trebuchet MS", Font.PLAIN, 24)); 
               JOptionPane.showMessageDialog(null, messageLabel);       
               name_txt.grabFocus();
               return false;
        }
       if(roll_txt.getText().trim().isEmpty())
        {
               String message = "Please Enter Student Roll Number";
               JLabel messageLabel = new JLabel(message);
               messageLabel.setFont(new Font("Trebuchet MS", Font.PLAIN, 24)); 
               JOptionPane.showMessageDialog(null, messageLabel);       
               roll_txt.grabFocus();
               return false;
        }
       if(dept_txt.getText().trim().isEmpty())
        {
               String message = "Please Enter Student Department";
               JLabel messageLabel = new JLabel(message);
               messageLabel.setFont(new Font("Trebuchet MS", Font.PLAIN, 24)); 
               JOptionPane.showMessageDialog(null, messageLabel);             
               dept_txt.grabFocus();
               return false;
        }
        return true;
    }
    
    private void clearData()
    {
        name_txt.setText("");          roll_txt.setText("");
        dept_txt.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delete_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delete_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delete_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delete_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delete_student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dept_lbl;
    private javax.swing.JTextField dept_txt;
    private javax.swing.JButton dlt_btn;
    private javax.swing.JButton exit_btn;
    private javax.swing.JButton home_btn;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JTextField name_txt;
    private javax.swing.JLabel roll_lbl;
    private javax.swing.JTextField roll_txt;
    // End of variables declaration//GEN-END:variables
}
