/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student_management_system;
import java.awt.event.*;
import java.awt.*;
import java.sql.*;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Hanseeka Dhingana
 */
public class Search_student extends javax.swing.JFrame {

    /**
     * Creates new form Search_student
     */
    static int row=-1;
    public Search_student() {
        setUndecorated(true);
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        exit_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        home_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbl_name = new javax.swing.JLabel();
        name_txt = new javax.swing.JTextField();
        add_btn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DataTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Search Student");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(374, 66, 528, 110);

        exit_btn.setBackground(new java.awt.Color(0, 0, 0));
        exit_btn.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        exit_btn.setForeground(new java.awt.Color(255, 255, 255));
        exit_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student_management_system/cross-removebg-preview.png"))); // NOI18N
        exit_btn.setContentAreaFilled(false);
        exit_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });
        jPanel1.add(exit_btn);
        exit_btn.setBounds(1133, 11, 66, 66);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student_management_system/search_cartoon-removebg-preview.png"))); // NOI18N
        jLabel5.setText(" ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(253, 33, 154, 154);

        home_btn.setBackground(new java.awt.Color(0, 0, 0));
        home_btn.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        home_btn.setForeground(new java.awt.Color(255, 255, 255));
        home_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student_management_system/home-removebg-preview.png"))); // NOI18N
        home_btn.setContentAreaFilled(false);
        home_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_btnActionPerformed(evt);
            }
        });
        jPanel1.add(home_btn);
        home_btn.setBounds(11, 11, 99, 77);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        lbl_name.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lbl_name.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student_management_system/Search-removebg-preview.png"))); // NOI18N
        jPanel2.add(lbl_name);
        lbl_name.setBounds(264, 66, 66, 66);

        name_txt.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        name_txt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        name_txt.setCaretColor(new java.awt.Color(255, 255, 255));
        name_txt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        name_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_txtActionPerformed(evt);
            }
        });
        name_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                name_txtKeyReleased(evt);
            }
        });
        jPanel2.add(name_txt);
        name_txt.setBounds(330, 66, 528, 66);

        add_btn.setBackground(new java.awt.Color(0, 153, 51));
        add_btn.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        add_btn.setForeground(new java.awt.Color(255, 255, 255));
        add_btn.setText("Filter");
        add_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });
        jPanel2.add(add_btn);
        add_btn.setBounds(473, 143, 165, 44);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student_management_system/arrow-removebg-preview.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(858, 55, 77, 77);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N

        DataTable.setAutoCreateRowSorter(true);
        DataTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        DataTable.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        DataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "No.", "Name", "Roll Number", "Department", "Grade", "Status"
            }
        ));
        DataTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        DataTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DataTable.setDropMode(javax.swing.DropMode.INSERT_ROWS);
        DataTable.setFillsViewportHeight(true);
        DataTable.setName(""); // NOI18N
        DataTable.setRowHeight(30);
        DataTable.setSelectionBackground(new java.awt.Color(255, 255, 255));
        DataTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        DataTable.setSurrendersFocusOnKeystroke(true);
        jScrollPane1.setViewportView(DataTable);
        DataTable.getAccessibleContext().setAccessibleName("");
        DataTable.getAccessibleContext().setAccessibleDescription("");

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(121, 275, 968, 143);

        jLabel1.setText("______________________________________________________");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(330, 110, 495, 33);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1219, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
      String message = "Do you want to exit";
        JLabel messageLabel = new JLabel(message);
        messageLabel.setFont(new Font("Trebuchet MS", Font.PLAIN, 24)); 
        int check =JOptionPane.showConfirmDialog(null,messageLabel,"Confirmation", JOptionPane.YES_NO_OPTION);
        
        if(check==JOptionPane.YES_OPTION)
        {
            
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
         Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
        }
    }//GEN-LAST:event_exit_btnActionPerformed

    private void name_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_txtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void home_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_btnActionPerformed
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);

        Student_management_system open = new Student_management_system();
        open.setVisible(true);
    }//GEN-LAST:event_home_btnActionPerformed

    private void name_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_name_txtKeyReleased
       
        
    }//GEN-LAST:event_name_txtKeyReleased

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        // TODO add your handling code here:
        String searchStudent =name_txt.getText();
        DefaultTableModel model = (DefaultTableModel) DataTable.getModel();
        DataTable.setModel(model);
        if(!name_txt.getText().trim().isEmpty()){
        
        // Establish a database connection
        try (Connection connection = ConnectionProvider.getCon()) {
            // Create a PreparedStatement with a SELECT query
            String query = "SELECT * FROM student_registor WHERE Student_name = ?";
            try (PreparedStatement preparedStatement = connection.prepareStatement(query)) {
                // Set the search parameter in the PreparedStatement
                preparedStatement.setString(1, searchStudent);

                // Execute the query and get the result set
                try (ResultSet resultSet = preparedStatement.executeQuery()) {
                    // Process the result set
                    while (resultSet.next()) {
                        // Retrieve and print data from the result set
                        String number = resultSet.getString("No.");
                        String column1Data = resultSet.getString("Student_name");
                        String column2Data = resultSet.getString("Roll_number");
                        String column3Data=resultSet.getString("Student_depart");
                        String column4Data=resultSet.getString("Student_grade");
                    
                      model.insertRow(++row,new Object[]{number,column1Data,column2Data,column3Data,column4Data,"Available"});
                    }
                   
                }
            }
        } 
       catch (Exception e) {
           JOptionPane.showMessageDialog(null, "This Student Not Available ");
        }
        }
        
        else{
               String message = "Please Enter Student Name";
               JLabel messageLabel = new JLabel(message);
               messageLabel.setFont(new Font("Trebuchet MS", Font.PLAIN, 24)); 
               JOptionPane.showMessageDialog(null, messageLabel);             
        }
    }//GEN-LAST:event_add_btnActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search_student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DataTable;
    private javax.swing.JButton add_btn;
    private javax.swing.JButton exit_btn;
    private javax.swing.JButton home_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JTextField name_txt;
    // End of variables declaration//GEN-END:variables
}
