/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student_management_system;

import java.awt.event.*;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author Hanseeka Dhingana
 */
public class Student_management_system extends javax.swing.JFrame {

    /**
     * Creates new form Student_management_system
     */
    public Student_management_system() {
        setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        exit_btn1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        dlt_btn = new javax.swing.JButton();
        search_btn = new javax.swing.JButton();
        Add_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Student Management System");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(351, 62, 528, 110);

        exit_btn1.setBackground(new java.awt.Color(0, 0, 0));
        exit_btn1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        exit_btn1.setForeground(new java.awt.Color(255, 255, 255));
        exit_btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student_management_system/cross-removebg-preview.png"))); // NOI18N
        exit_btn1.setContentAreaFilled(false);
        exit_btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(exit_btn1);
        exit_btn1.setBounds(1144, 11, 66, 66);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student_management_system/teacher-removebg-preview.png"))); // NOI18N
        jLabel5.setText(" ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(187, 44, 154, 154);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        dlt_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student_management_system/delete student.png"))); // NOI18N
        dlt_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        dlt_btn.setContentAreaFilled(false);
        dlt_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dlt_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlt_btnActionPerformed(evt);
            }
        });
        jPanel2.add(dlt_btn);
        dlt_btn.setBounds(506, 198, 198, 187);

        search_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student_management_system/search student.png"))); // NOI18N
        search_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        search_btn.setContentAreaFilled(false);
        search_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });
        jPanel2.add(search_btn);
        search_btn.setBounds(781, 198, 198, 187);

        Add_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student_management_system/add student.jpg"))); // NOI18N
        Add_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Add_btn.setContentAreaFilled(false);
        Add_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_btnActionPerformed(evt);
            }
        });
        jPanel2.add(Add_btn);
        Add_btn.setBounds(231, 198, 198, 187);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("Add Student");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(264, 330, 132, 21);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setText("Delete Student\n");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(539, 330, 132, 21);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setText("Search Student");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(814, 330, 132, 21);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1220, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
        
        Search_student open = new Search_student();
        open.setVisible(true);
    }//GEN-LAST:event_search_btnActionPerformed

    private void dlt_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlt_btnActionPerformed
       WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
        
        Delete_student open = new Delete_student();
        open.setVisible(true);
    }//GEN-LAST:event_dlt_btnActionPerformed

    private void Add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_btnActionPerformed
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);

        Add_student open = new Add_student();
        open.setVisible(true);
    }//GEN-LAST:event_Add_btnActionPerformed

    private void exit_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btn1ActionPerformed
        String message = "Do you want to exit";
        JLabel messageLabel = new JLabel(message);
        messageLabel.setFont(new Font("Trebuchet MS", Font.PLAIN, 24)); 
        int check =JOptionPane.showConfirmDialog(null,messageLabel,"Confirmation", JOptionPane.YES_NO_OPTION);
        
        if(check==JOptionPane.YES_OPTION)
        {
            
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
         Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
        }
    }//GEN-LAST:event_exit_btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_management_system.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_management_system.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_management_system.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_management_system.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_management_system().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_btn;
    private javax.swing.JButton dlt_btn;
    private javax.swing.JButton exit_btn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton search_btn;
    // End of variables declaration//GEN-END:variables
}
