/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student_grade_calculator;

import javafx.scene.paint.Color;
import static javafx.scene.paint.Color.color;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Hanseeka Dhingana
 */
public class Student_Grade_Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Student_Grade_Calculator
     */
    public Student_Grade_Calculator() {
        setUndecorated(true);
        initComponents();
    }
     static double sum=0;
     static int Total_sub=0;
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_average = new javax.swing.JLabel();
        txt_average = new javax.swing.JTextField();
        lbl_average1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_outof = new javax.swing.JLabel();
        txt_cource = new javax.swing.JTextField();
        txt_mark = new javax.swing.JTextField();
        txt_outof = new javax.swing.JTextField();
        lbl_cource = new javax.swing.JLabel();
        lbl_mark = new javax.swing.JLabel();
        btn_calculate = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        lbl_grade = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        txt_grade = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(78, 153, 103));
        jPanel1.setLayout(null);

        lbl_average.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        lbl_average.setForeground(new java.awt.Color(255, 255, 255));
        lbl_average.setText("     Grade Calculator ");
        jPanel1.add(lbl_average);
        lbl_average.setBounds(33, 0, 528, 110);

        txt_average.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        txt_average.setForeground(new java.awt.Color(255, 153, 102));
        txt_average.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txt_average.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_averageActionPerformed(evt);
            }
        });
        jPanel1.add(txt_average);
        txt_average.setBounds(374, 121, 143, 55);

        lbl_average1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lbl_average1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_average1.setText("Your Average is : ");
        jPanel1.add(lbl_average1);
        lbl_average1.setBounds(55, 77, 341, 132);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        lbl_outof.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lbl_outof.setText("Out Of");
        jPanel2.add(lbl_outof);
        lbl_outof.setBounds(341, 187, 176, 33);

        txt_cource.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txt_cource.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_cource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_courceActionPerformed(evt);
            }
        });
        jPanel2.add(txt_cource);
        txt_cource.setBounds(55, 77, 473, 66);

        txt_mark.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txt_mark.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_mark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_markActionPerformed(evt);
            }
        });
        jPanel2.add(txt_mark);
        txt_mark.setBounds(55, 220, 176, 66);

        txt_outof.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txt_outof.setText("100");
        txt_outof.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txt_outof);
        txt_outof.setBounds(341, 220, 187, 66);

        lbl_cource.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lbl_cource.setText("Cource ");
        jPanel2.add(lbl_cource);
        lbl_cource.setBounds(55, 44, 176, 33);

        lbl_mark.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lbl_mark.setText("Marks Obtained ");
        jPanel2.add(lbl_mark);
        lbl_mark.setBounds(55, 187, 209, 33);

        btn_calculate.setBackground(new java.awt.Color(78, 153, 78));
        btn_calculate.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btn_calculate.setForeground(new java.awt.Color(255, 255, 255));
        btn_calculate.setText("Calculate ");
        btn_calculate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calculateActionPerformed(evt);
            }
        });
        jPanel2.add(btn_calculate);
        btn_calculate.setBounds(44, 550, 506, 55);

        btn_clear.setBackground(new java.awt.Color(255, 255, 255));
        btn_clear.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btn_clear.setText("Clear all\n");
        btn_clear.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_clear.setBorderPainted(false);
        btn_clear.setContentAreaFilled(false);
        btn_clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel2.add(btn_clear);
        btn_clear.setBounds(44, 616, 506, 44);

        btn_add.setBackground(new java.awt.Color(255, 255, 255));
        btn_add.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btn_add.setForeground(new java.awt.Color(103, 153, 78));
        btn_add.setText("+Add more");
        btn_add.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(103, 153, 78), 2, true));
        btn_add.setContentAreaFilled(false);
        btn_add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel2.add(btn_add);
        btn_add.setBounds(55, 308, 473, 44);

        lbl_grade.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lbl_grade.setText("Your Grade is:  ");
        jPanel2.add(lbl_grade);
        lbl_grade.setBounds(55, 429, 286, 55);

        lbl_total.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lbl_total.setText("Your Total Marks is: ");
        jPanel2.add(lbl_total);
        lbl_total.setBounds(55, 363, 286, 55);

        txt_grade.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txt_grade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txt_grade);
        txt_grade.setBounds(418, 429, 110, 55);

        txt_total.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txt_total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txt_total);
        txt_total.setBounds(418, 363, 110, 55);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_markActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_markActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_markActionPerformed

    private void txt_courceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_courceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_courceActionPerformed

    private void txt_averageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_averageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_averageActionPerformed

    private void btn_calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calculateActionPerformed
       if(!txt_mark.getText().trim().isEmpty())
          {
               sum+=Double.valueOf(txt_mark.getText());
               Total_sub++;
          }
        double Average = (sum/Total_sub);
        txt_total.setText(String.valueOf(sum));
        txt_average.setText(String.valueOf(Average)+"%");
        
        if(Average>=93 && Average<=100)
            txt_grade.setText("A");
        if(Average>=90 && Average<=92)
            txt_grade.setText("A-");
        if(Average>= 87 && Average<=89)
            txt_grade.setText("B+");
        if(Average>=83 && Average<=86)
            txt_grade.setText("B");
        if(Average>=80 && Average<=82)
            txt_grade.setText("B-");
        if(Average>=77 && Average<=79)
            txt_grade.setText("C+");
        if(Average>=73 && Average<=76)
            txt_grade.setText("C");
        if(Average>=70 && Average<=72)
            txt_grade.setText("C-");
        if(Average>=67 && Average<=69)
            txt_grade.setText("D+");
        if(Average>=60 && Average<=66)
            txt_grade.setText("D");
        if(Average>=0 && Average<=59)
            txt_grade.setText("F");
    }//GEN-LAST:event_btn_calculateActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        sum+=Double.valueOf(txt_mark.getText());
        Total_sub++;

        txt_mark.setText("");
        txt_cource.setText("");

    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        txt_average.setText("");               txt_mark.setText("");
        txt_cource.setText("");                txt_total.setText("");
        txt_grade.setText("");
    
    }//GEN-LAST:event_btn_clearActionPerformed

  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Grade_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Grade_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Grade_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Grade_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_Grade_Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_calculate;
    private javax.swing.JButton btn_clear;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_average;
    private javax.swing.JLabel lbl_average1;
    private javax.swing.JLabel lbl_cource;
    private javax.swing.JLabel lbl_grade;
    private javax.swing.JLabel lbl_mark;
    private javax.swing.JLabel lbl_outof;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JTextField txt_average;
    private javax.swing.JTextField txt_cource;
    private javax.swing.JTextField txt_grade;
    private javax.swing.JTextField txt_mark;
    private javax.swing.JTextField txt_outof;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables

  

    
}
