/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Number_Game;
import java.awt.*;
import java.awt.event.*;
import java.util.*;
import javax.swing.*;
import java.math.*;

/**
 *
 * @author Hanseeka Dhingana
 */
public class Play extends javax.swing.JFrame {

    /**
     * Creates new form Play
     */
    public Play() {
        initComponents();
    }
     static int score=0;
    static int limit =6;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        lbl_back = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_limit = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_score1 = new javax.swing.JTextField();
        lbl_cont = new javax.swing.JLabel();
        txt_guess = new javax.swing.JTextField();
        btn_enter = new javax.swing.JButton();
        txt_comment = new javax.swing.JTextField();
        txt_number = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_back.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        lbl_back.setForeground(new java.awt.Color(255, 255, 255));
        lbl_back.setText("EXIT");
        lbl_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_backMouseClicked(evt);
            }
        });
        lbl_back.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                lbl_backCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lbl_backInputMethodTextChanged(evt);
            }
        });
        jPanel1.add(lbl_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 55, 132, 55));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Guess the number");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 66, 517, 66));

        lbl_limit.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        lbl_limit.setForeground(new java.awt.Color(255, 255, 255));
        lbl_limit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_limit, new org.netbeans.lib.awtextra.AbsoluteConstraints(781, 297, 319, 44));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 473, 231, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Score:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(825, 352, 99, 44));

        txt_score1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txt_score1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_score1, new org.netbeans.lib.awtextra.AbsoluteConstraints(924, 363, 110, -1));

        lbl_cont.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        lbl_cont.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cont.setText("Continue playing!");
        lbl_cont.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_cont.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_contMouseClicked(evt);
            }
        });
        jPanel1.add(lbl_cont, new org.netbeans.lib.awtextra.AbsoluteConstraints(814, 407, 330, 55));

        txt_guess.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        txt_guess.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_guess.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_guess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_guessActionPerformed(evt);
            }
        });
        jPanel1.add(txt_guess, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 473, 242, 66));

        btn_enter.setBackground(new java.awt.Color(0, 51, 102));
        btn_enter.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btn_enter.setForeground(new java.awt.Color(255, 255, 255));
        btn_enter.setText("Enter");
        btn_enter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enterActionPerformed(evt);
            }
        });
        jPanel1.add(btn_enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 473, 220, 66));

        txt_comment.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        txt_comment.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_comment.setText("Enter the number");
        txt_comment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_commentActionPerformed(evt);
            }
        });
        jPanel1.add(txt_comment, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 330, 440, 55));

        txt_number.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        txt_number.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_number.setText("?");
        txt_number.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_numberActionPerformed(evt);
            }
        });
        jPanel1.add(txt_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 242, 440, 66));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Between 1 to 100");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 132, 385, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("You have 6 chances");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(781, 253, 385, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Number_Game/question mark.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-11, 0, 1287, 902));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_backInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lbl_backInputMethodTextChanged
        
    }//GEN-LAST:event_lbl_backInputMethodTextChanged

    private void lbl_backCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lbl_backCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_backCaretPositionChanged

    private void lbl_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backMouseClicked
       // method use for yes or no confirmation box
        int check =JOptionPane.showConfirmDialog(null,"Do you want to exit!","Confirmation", JOptionPane.YES_NO_OPTION);
        
        if(check==JOptionPane.YES_OPTION)
        {
            Score_page obj = new Score_page();
            obj.setVisible(true);
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
         Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
         
            String score_str = String.valueOf(score);
            obj.txt_score.setText(score_str);
            
            if(limit==0)
            {
                String guess_str= String.valueOf(0);
                obj.txt_guess.setText(guess_str);
            }
           String guess_str= String.valueOf(6-limit);
            obj.txt_guess.setText(guess_str);
        }  
    
        else {
               txt_guess.setText("");      txt_number.setText("?");
                 txt_comment.setText("Enter the number");       
        }
    }//GEN-LAST:event_lbl_backMouseClicked

    private void txt_commentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_commentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_commentActionPerformed

    private void txt_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_numberActionPerformed
        
    }//GEN-LAST:event_txt_numberActionPerformed

    private void btn_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enterActionPerformed
         
         Integer num = Integer.valueOf(txt_guess.getText());
         boolean str = txt_guess.getText( ).trim( ).isEmpty( );
        
        if(str)
          {
               JOptionPane.showMessageDialog(this, "Please Enter Number");
               txt_guess.setText("");
               txt_guess.grabFocus();
          }
          else if (num<1 || num>100)
          {
              JOptionPane.showMessageDialog(this, "Please enter the between 1 to 100");
              txt_guess.setText("");         
          }
        else {
                  check();  
            }
        
         limit--;
           String guess_str= String.valueOf(6-limit);
           
         if(limit==0)
        {
          
         WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
         Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
         Score_page obj = new Score_page();
         obj.setVisible(true);
         
            String score_str = String.valueOf(score);
            obj.txt_score.setText(score_str);
            obj.txt_guess.setText(guess_str);
          }
             lbl_limit.setText(guess_str);
    }//GEN-LAST:event_btn_enterActionPerformed

    private void txt_guessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_guessActionPerformed
       
    }//GEN-LAST:event_txt_guessActionPerformed

    private void lbl_contMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_contMouseClicked
        txt_guess.setText("");      txt_number.setText("?");
        txt_comment.setText("Enter the number");     
          
    }//GEN-LAST:event_lbl_contMouseClicked
    private void check()
    {
        Integer guess = Integer.valueOf(txt_guess.getText());
        
        String num = generate();
        Integer num2 = Integer.valueOf(num);
      
        if(guess>num2)
        {
            txt_comment.setText("too high try again!");
            txt_number.setText(num);
            
        }
        else if(guess<num2)
        {
            txt_comment.setText("too low try again!");
            txt_number.setText(num);
           
        }
        else {
            txt_comment.setText("Correct");
            txt_number.setText(num);
            score++;
            String str = String.valueOf(score);
            txt_score1.setText(str);
        }        
        
    }

    private String generate()
    {
        Random obj = new Random();
        int min=1;
       int num =(int)Math.floor(Math.random() * (max - min + 1) + min);
       String num2= String.valueOf(num);
        return num2;
    }
    /**
     * @param args the command line arguments
     */        int max=100;

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Play().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_enter;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel lbl_back;
    private javax.swing.JLabel lbl_cont;
    private javax.swing.JLabel lbl_limit;
    private javax.swing.JTextField txt_comment;
    private javax.swing.JTextField txt_guess;
    private javax.swing.JTextField txt_number;
    private javax.swing.JTextField txt_score1;
    // End of variables declaration//GEN-END:variables
}
